### ISSUE TITLE
Compilation breaks on x64CPUDetect.cpp, line 41

### ISSUE THREAD

**Issue by billywade** [Tinob/Ishiiruka#114]
I recently upgraded my system (Manjaro) and compilation breaks, throwing this as an error. This file is a little old compared to upstream, as is most of the base source. Is this just a matter of figuring out what can be merged without breaking functionality?

**Comment by Tinob** [comment]
this happends in the stable or the latest version?

**Comment by Tinob** [comment]
also can you share the full compilation log?

**Comment by billywade** [comment]
Latest git. I'll post it a little later today when I can run compilation again.

**Comment by billywade** [comment]
Here's the error message:
```
[ 48%] Building CXX object Source/Core/Common/CMakeFiles/common.dir/x64ABI.cpp.o
[ 48%] Building CXX object Source/Core/Common/CMakeFiles/common.dir/x64Emitter.cpp.o
[ 48%] Building CXX object Source/Core/Common/CMakeFiles/common.dir/Logging/ConsoleListenerNix.cpp.o
[ 48%] Building CXX object Source/Core/Common/CMakeFiles/common.dir/x64FPURoundMode.cpp.o
[ 48%] Building CXX object Source/Core/Common/CMakeFiles/common.dir/x64CPUDetect.cpp.o
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/x64CPUDetect.cpp:41:12: error: ambiguating new declaration of ‘u64 _xgetbv(u32)’
 static u64 _xgetbv(u32 index)
            ^~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include/x86intrin.h:74,
                 from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/Intrinsics.h:30,
                 from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/x64CPUDetect.cpp:10:
/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include/xsaveintrin.h:60:1: note: old declaration ‘long long int _xgetbv(unsigned int)’
 _xgetbv (unsigned int __A)
 ^~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/x64CPUDetect.cpp:41:12: warning: ‘u64 _xgetbv(u32)’ defined but not used [-Wunused-function]
 static u64 _xgetbv(u32 index)
            ^~~~~~~
make[2]: *** [Source/Core/Common/CMakeFiles/common.dir/build.make:648: Source/Core/Common/CMakeFiles/common.dir/x64CPUDetect.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:910: Source/Core/Common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by DarkPhoenix10** [comment]
same is happening to me too

**Comment by Tinob** [comment]
just pushed a new version can you verify that id fixed?

**Comment by KAMiKAZOW** [comment]
Before that commit, only GCC 8 was affected. Now nothing works: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin-unstable/openSUSE_Tumbleweed/x86_64 (This is with wxWidgets 3.1 provided by the OS using GCC 7)

Fedora 28, which does not have wxWidgets 3.1 (therefore using the bundled one) but uses GCC 8 is still building: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin-unstable/Fedora_28/x86_64

**Comment by Tinob** [comment]
should be fixed now

**Comment by KAMiKAZOW** [comment]
Recompiling. The Stable branch, btw, is also affected: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin/Fedora_28/x86_64

**Comment by KAMiKAZOW** [comment]
Git master still failing: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin-unstable/Fedora_28/x86_64

**Comment by billywade** [comment]
Just tried to compile:
```
[ 65%] Building CXX object Source/Core/VideoCommon/CMakeFiles/videocommon.dir/XFStructs.cpp.o
[ 65%] Building CXX object Source/Core/VideoCommon/CMakeFiles/videocommon.dir/x64TextureDecoder.cpp.o
[ 66%] Building CXX object Source/Core/VideoCommon/CMakeFiles/videocommon.dir/VertexLoaderX64.cpp.o
[ 66%] Building CXX object Source/Core/VideoCommon/CMakeFiles/videocommon.dir/AVIDump.cpp.o
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp: In function ‘void InitAVCodec()’:
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:60:21: warning: ‘void av_register_all()’ is deprecated [-Wdeprecated-declarations]
     av_register_all();
                     ^
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:2025:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:60:21: warning: ‘void av_register_all()’ is deprecated [-Wdeprecated-declarations]
     av_register_all();
                     ^
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:2025:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp: In static member function ‘static bool AVIDump::CreateVideoFile()’:
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:184:31: error: ‘CODEC_FLAG_GLOBAL_HEADER’ was not declared in this scope
     s_codec_context->flags |= CODEC_FLAG_GLOBAL_HEADER;
                               ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:184:31: note: suggested alternative: ‘AV_CODEC_FLAG_GLOBAL_HEADER’
     s_codec_context->flags |= CODEC_FLAG_GLOBAL_HEADER;
                               ^~~~~~~~~~~~~~~~~~~~~~~~
                               AV_CODEC_FLAG_GLOBAL_HEADER
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:20:
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:215:70: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
 TICE_LOG(VIDEO, "Opening file %s for dumping", s_format_context->filename);
                                                                  ^~~~~~~~

/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/Logging/Log.h:96:44: note: in definition of macro ‘GENERIC_LOG’
       GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__);                                           \
                                            ^~~~~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:215:3: note: in expansion of macro ‘NOTICE_LOG’
   NOTICE_LOG(VIDEO, "Opening file %s for dumping", s_format_context->filename);
   ^~~~~~~~~~
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:20:
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:215:70: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
 TICE_LOG(VIDEO, "Opening file %s for dumping", s_format_context->filename);
                                                                  ^~~~~~~~

/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/Logging/Log.h:96:44: note: in definition of macro ‘GENERIC_LOG’
       GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__);                                           \
                                            ^~~~~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:215:3: note: in expansion of macro ‘NOTICE_LOG’
   NOTICE_LOG(VIDEO, "Opening file %s for dumping", s_format_context->filename);
   ^~~~~~~~~~
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:20:
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:215:70: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
 TICE_LOG(VIDEO, "Opening file %s for dumping", s_format_context->filename);
                                                                  ^~~~~~~~

/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/Logging/Log.h:96:44: note: in definition of macro ‘GENERIC_LOG’
       GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__);                                           \
                                            ^~~~~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:215:3: note: in expansion of macro ‘NOTICE_LOG’
   NOTICE_LOG(VIDEO, "Opening file %s for dumping", s_format_context->filename);
   ^~~~~~~~~~
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:216:58: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
   if (avio_open(&s_format_context->pb, s_format_context->filename, AVIO_FLAG_WRITE) < 0 ||
                                                          ^~~~~~~~
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:216:58: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
   if (avio_open(&s_format_context->pb, s_format_context->filename, AVIO_FLAG_WRITE) < 0 ||
                                                          ^~~~~~~~
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:216:58: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
   if (avio_open(&s_format_context->pb, s_format_context->filename, AVIO_FLAG_WRITE) < 0 ||
                                                          ^~~~~~~~
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:20:
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:219:61: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
     ERROR_LOG(VIDEO, "Could not open %s", s_format_context->filename);
                                                             ^~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/Logging/Log.h:96:44: note: in definition of macro ‘GENERIC_LOG’
       GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__);                                           \
                                            ^~~~~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:219:5: note: in expansion of macro ‘ERROR_LOG’
     ERROR_LOG(VIDEO, "Could not open %s", s_format_context->filename);
     ^~~~~~~~~
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:20:
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:219:61: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
     ERROR_LOG(VIDEO, "Could not open %s", s_format_context->filename);
                                                             ^~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/Logging/Log.h:96:44: note: in definition of macro ‘GENERIC_LOG’
       GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__);                                           \
                                            ^~~~~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:219:5: note: in expansion of macro ‘ERROR_LOG’
     ERROR_LOG(VIDEO, "Could not open %s", s_format_context->filename);
     ^~~~~~~~~
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:20:
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:219:61: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
     ERROR_LOG(VIDEO, "Could not open %s", s_format_context->filename);
                                                             ^~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/Common/Logging/Log.h:96:44: note: in definition of macro ‘GENERIC_LOG’
       GenericLog(v, t, __FILE__, __LINE__, __VA_ARGS__);                                           \
                                            ^~~~~~~~~~~
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:219:5: note: in expansion of macro ‘ERROR_LOG’
     ERROR_LOG(VIDEO, "Could not open %s", s_format_context->filename);
     ^~~~~~~~~
In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:223:90: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
 gFromFormat("Dumping Frames to \"%s\" (%dx%d)", s_format_context->filename,
                                                                   ^~~~~~~~

In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:223:90: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
 gFromFormat("Dumping Frames to \"%s\" (%dx%d)", s_format_context->filename,
                                                                   ^~~~~~~~

In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
/tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:223:90: warning: ‘AVFormatContext::filename’ is deprecated [-Wdeprecated-declarations]
 gFromFormat("Dumping Frames to \"%s\" (%dx%d)", s_format_context->filename,
                                                                   ^~~~~~~~

In file included from /tmp/pamac-build-user/dolphin-emu-ishiiruka-git/src/dolphin-emu/Source/Core/VideoCommon/AVIDump.cpp:14:
/usr/include/libavformat/avformat.h:1408:23: note: declared here
     char filename[1024];
                       ^
make[2]: *** [Source/Core/VideoCommon/CMakeFiles/videocommon.dir/build.make:1077: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/AVIDump.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1325: Source/Core/VideoCommon/CMakeFiles/videocommon.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...


```

**Comment by DarkPhoenix10** [comment]
i'm getting the same error too :p

**Comment by billywade** [comment]
Tinob's getting us further, though. I'm glad!

**Comment by KAMiKAZOW** [comment]
Not yet:

```
[ 1782s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180521+git.1d0dc41cc/Source/Core/DiscIO/VolumeGC.cpp:38:3:   required from here
[ 1782s] /usr/include/c++/8/variant:254:42: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = DiscIO::FileSystem; _Dp = std::default_delete<DiscIO::FileSystem>]'
[ 1782s]        __variant::__ref_cast<_Lhs>(__lhs) = __variant::__ref_cast<_Rhs>(__rhs);
[ 1782s]        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 1782s] In file included from /usr/include/c++/8/memory:80,
[ 1782s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180521+git.1d0dc41cc/Source/Core/DiscIO/VolumeGC.cpp:8:
[ 1782s] /usr/include/c++/8/bits/unique_ptr.h:395:19: note: declared here
[ 1782s]        unique_ptr& operator=(const unique_ptr&) = delete;
[ 1782s]                    ^~~~~~~~
[ 1782s] In file included from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180521+git.1d0dc41cc/Source/Core/Common/Compat/variant:8,
[ 1782s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180521+git.1d0dc41cc/Source/Core/Common/Lazy.h:9,
[ 1782s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180521+git.1d0dc41cc/Source/Core/DiscIO/VolumeGC.h:14,
[ 1782s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180521+git.1d0dc41cc/Source/Core/DiscIO/VolumeGC.cpp:27:
[ 1782s] /usr/include/c++/8/variant: In instantiation of 'void std::__detail::__variant::__erased_ctor(void*, void*) [with _Lhs = std::unique_ptr<DiscIO::FileSystem>&; _Rhs = const std::unique_ptr<DiscIO::FileSystem>&]':
[ 1782s] /usr/include/c++/8/variant:465:30:   required from 'std::__detail::__variant::_Copy_ctor_base<<anonymous>, _Types>::_Copy_ctor_base(const std::__detail::__variant::_Copy_ctor_base<<anonymous>, _Types>&) [with bool <anonymous> = false; _Types = {std::unique_ptr<DiscIO::FileSystem, std::default_delete<DiscIO::FileSystem> >, std::function<std::unique_ptr<DiscIO::FileSystem, std::default_delete<DiscIO::FileSystem> >()>}]'
[ 1782s] /usr/include/c++/8/variant:506:7:   required from 'std::__detail::__variant::_Move_assign_base<<anonymous>, _Types>& std::__detail::__variant::_Move_assign_base<<anonymous>, _Types>::operator=(std::__detail::__variant::_Move_assign_base<<anonymous>, _Types>&&) [with bool <anonymous> = false; _Types = {std::unique_ptr<DiscIO::FileSystem, std::default_delete<DiscIO::FileSystem> >, std::function<std::unique_ptr<DiscIO::FileSystem, std::default_delete<DiscIO::FileSystem> >()>}]'
[ 1782s] /usr/include/c++/8/variant:645:12:   required from 'const Common::Lazy<T>& Common::Lazy<T>::operator=(std::variant<T, std::function<T()> >&&) [with T = std::unique_ptr<DiscIO::FileSystem>]'
[ 1782s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180521+git.1d0dc41cc/Source/Core/DiscIO/VolumeGC.cpp:38:3:   required from here
[ 1782s] /usr/include/c++/8/variant:242:7: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = DiscIO::FileSystem; _Dp = std::default_delete<DiscIO::FileSystem>]'
[ 1782s]        ::new (__lhs) _Type(__variant::__ref_cast<_Rhs>(__rhs));
[ 1782s]        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 1782s] In file included from /usr/include/c++/8/memory:80,
[ 1782s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180521+git.1d0dc41cc/Source/Core/DiscIO/VolumeGC.cpp:8:
[ 1782s] /usr/include/c++/8/bits/unique_ptr.h:394:7: note: declared here
[ 1782s]        unique_ptr(const unique_ptr&) = delete;
[ 1782s]        ^~~~~~~~~~
[ 1782s] make[2]: *** [Source/Core/DiscIO/CMakeFiles/discio.dir/build.make:271: Source/Core/DiscIO/CMakeFiles/discio.dir/VolumeGC.cpp.o] Error 1
[ 1782s] make[1]: *** [CMakeFiles/Makefile2:1020: Source/Core/DiscIO/CMakeFiles/discio.dir/all] Error 2
[ 1782s] make: *** [Makefile:152: all] Error 2

```

**Comment by billywade** [comment]
Just clarifying, can everyone compile upstream fine? I want to make sure that this is a problem for Ishiiruka and I don't need to escalate this to the Dolphin dev team.

**Comment by KAMiKAZOW** [comment]
> Just clarifying, can everyone compile upstream fine?

No, upstream Dolphin also suffers from a GCC8 incompatibility problem: https://bugs.dolphin-emu.org/issues/11047

However, the workarounds used for upstream Dolphin didn't work for me for Ishiiruka.

**Comment by billywade** [comment]
Good to know. I always download from Arch package list, but I imagine that'll help Ishiiruka's devs.

**Comment by Tinob** [comment]
can you try now?

**Comment by KAMiKAZOW** [comment]
Doesn't work: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin-unstable/Fedora_28/x86_64

**Comment by billywade** [comment]
It does compile up for me, so I figure the absolute latest has something the nearest stable doesn't.

**Comment by DarkPhoenix10** [comment]
works for me too, fixed?

**Comment by KAMiKAZOW** [comment]
> fixed?

Impossible. No commits since https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin-unstable/Fedora_28/x86_64 failed.

**Comment by billywade** [comment]
@DarkPhoenix10 what distro are you running?

**Comment by Tinob** [comment]
@KAMiKAZOW for some distros is already fixed, the problem with line 27 in VolumeGC.cpp is not present in all distros, im looking for a workaround to that issue but im little bussy at work rigth now.

**Comment by Tinob** [comment]
@KAMiKAZOW can you test the latest version?

**Comment by KAMiKAZOW** [comment]
```
[ 1105s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180525+git.b823ae185/Source/Core/DiscIO/VolumeGC.cpp:38:3:   required from here
[ 1105s] /usr/include/c++/8/variant:254:42: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = DiscIO::FileSystem; _Dp = std::default_delete<DiscIO::FileSystem>]'
[ 1105s]        __variant::__ref_cast<_Lhs>(__lhs) = __variant::__ref_cast<_Rhs>(__rhs);
[ 1105s]        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 1105s] In file included from /usr/include/c++/8/memory:80,
[ 1105s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180525+git.b823ae185/Source/Core/DiscIO/VolumeGC.cpp:8:
[ 1105s] /usr/include/c++/8/bits/unique_ptr.h:395:19: note: declared here
[ 1105s]        unique_ptr& operator=(const unique_ptr&) = delete;
[ 1105s]                    ^~~~~~~~
[ 1105s] In file included from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180525+git.b823ae185/Source/Core/Common/Compat/variant:8,
[ 1105s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180525+git.b823ae185/Source/Core/Common/Lazy.h:9,
[ 1105s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180525+git.b823ae185/Source/Core/DiscIO/VolumeGC.h:14,
[ 1105s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180525+git.b823ae185/Source/Core/DiscIO/VolumeGC.cpp:27:
[ 1105s] /usr/include/c++/8/variant: In instantiation of 'void std::__detail::__variant::__erased_ctor(void*, void*) [with _Lhs = std::unique_ptr<DiscIO::FileSystem>&; _Rhs = const std::unique_ptr<DiscIO::FileSystem>&]':
[ 1105s] /usr/include/c++/8/variant:465:30:   required from 'std::__detail::__variant::_Copy_ctor_base<<anonymous>, _Types>::_Copy_ctor_base(const std::__detail::__variant::_Copy_ctor_base<<anonymous>, _Types>&) [with bool <anonymous> = false; _Types = {std::unique_ptr<DiscIO::FileSystem, std::default_delete<DiscIO::FileSystem> >, std::function<std::unique_ptr<DiscIO::FileSystem, std::default_delete<DiscIO::FileSystem> >()>}]'
[ 1105s] /usr/include/c++/8/variant:506:7:   required from 'std::__detail::__variant::_Move_assign_base<<anonymous>, _Types>& std::__detail::__variant::_Move_assign_base<<anonymous>, _Types>::operator=(std::__detail::__variant::_Move_assign_base<<anonymous>, _Types>&&) [with bool <anonymous> = false; _Types = {std::unique_ptr<DiscIO::FileSystem, std::default_delete<DiscIO::FileSystem> >, std::function<std::unique_ptr<DiscIO::FileSystem, std::default_delete<DiscIO::FileSystem> >()>}]'
[ 1105s] /usr/include/c++/8/variant:645:12:   required from 'const Common::Lazy<T>& Common::Lazy<T>::operator=(std::variant<T, std::function<T()> >&&) [with T = std::unique_ptr<DiscIO::FileSystem>]'
[ 1105s] /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180525+git.b823ae185/Source/Core/DiscIO/VolumeGC.cpp:38:3:   required from here
[ 1105s] /usr/include/c++/8/variant:242:7: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = DiscIO::FileSystem; _Dp = std::default_delete<DiscIO::FileSystem>]'
[ 1105s]        ::new (__lhs) _Type(__variant::__ref_cast<_Rhs>(__rhs));
[ 1105s]        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 1105s] In file included from /usr/include/c++/8/memory:80,
[ 1105s]                  from /home/abuild/rpmbuild/BUILD/ishiiruka-dolphin-unstable-5.0.20180525+git.b823ae185/Source/Core/DiscIO/VolumeGC.cpp:8:
[ 1105s] /usr/include/c++/8/bits/unique_ptr.h:394:7: note: declared here
[ 1105s]        unique_ptr(const unique_ptr&) = delete;
[ 1105s]        ^~~~~~~~~~
[ 1105s] make[2]: *** [Source/Core/DiscIO/CMakeFiles/discio.dir/build.make:271: Source/Core/DiscIO/CMakeFiles/discio.dir/VolumeGC.cpp.o] Error 1
[ 1105s] make[1]: *** [CMakeFiles/Makefile2:1020: Source/Core/DiscIO/CMakeFiles/discio.dir/all] Error 2
[ 1105s] make: *** [Makefile:152: all] Error 2

```

https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:Emulators/ishiiruka-dolphin-unstable/Fedora_28/x86_64

**Comment by TiagoOrl** [comment]
Getting the same error on Ubuntu 19.04

**Comment by billywade** [comment]
@TiagoOrl you should probably open a new ticket, it's been almost a year since the last post on this issue. Really, since my original issue is solved, if @Tinob is cool with it I'll probably close this since the problem I had is probably totally unrelated to whatever a similar-looking issue is now.
