### ISSUE TITLE
Crash when disabling SSAO in custom PP shader during emulation

### ISSUE THREAD

**Issue by Fs00** [Tinob/Ishiiruka#115]
Enabling/disabling SSAO in the [attached shader](https://github.com/Tinob/Ishiiruka/files/2020576/Hamasaki.Vanilla.Ultra.glsl.txt) (a custom version of IshiirukaFX) from Video options during emulation leads to a crash in some scenarios. This happens with DX11/DX12 back-ends in v1057, as far as I've tested.
I don't know which version introduced the bug, since the one I was using before is 1017.

**Comment by Tinob** [comment]
this issue should be fixed in the latest 1063 version can you test it?

**Comment by Fs00** [comment]
Sadly it's not fixed, still crashes on Mario Galaxy for me. I've uploaded here my [config folder](https://github.com/Tinob/Ishiiruka/files/2041740/Config.zip) so you can test it.

**Comment by Tinob** [comment]
can you give more detail on how to reproduce it?

**Comment by Fs00** [comment]
It's still present in v1085.
