### ISSUE TITLE
[Feature Request] ROM-specific shader profiles

### ISSUE THREAD

**Issue by billywade** [Tinob/Ishiiruka#123]
I don't know enough cpp to implement this, but it would be neat to be able to save specific shader combinations for different ROMs, rather than have one master shader combination used on all games. 

I could see it working by putting in a check for a customization-XXXX.conf file equalling XXXX, where XXXX is the code for the ROM file, and those files being stored in Ishiiruka's configuration directory as named, saved versions of the existing shader config structure, and then loading them instead of the master. 

This may exist and I just haven't seen it yet.

**Comment by billywade** [comment]
Thanks boss. I always play in fullscreen, that's why I've missed it. After I tinker with it a bit, do you mind if I do a write up in the wiki about how to do universal and specific shaders?

**Comment by Tinob** [comment]
yes plese with my lack of time this days any help is good.

**Comment by billywade** [comment]
No prob, Bob. Hey, I'm getting a problem where Ishiiruka crashes if I try to change shaders mid-game.

**Comment by Tinob** [comment]
is easy to reproduce? can you give me more detail on the game and shaders your re trying?

**Comment by billywade** [comment]
Yeah, it was The Legend of Zelda: The Wind Waker, US version, and the shader was IshiirukaFXLight. I turned off SSGI in the internal options and it seized up on me.

**Comment by Tinob** [comment]
thanks fr the tip will take a look

**Comment by Tinob** [comment]
individual files are created for each shader, for each game
you can find them inside Documents\Dolphin Emulator\Load\ShaderPresets

**Comment by billywade** [comment]
Oh, alright, thanks.

**Comment by Tinob** [comment]
the crashes while changing the options should be fixed in the last version.

**Comment by billywade** [comment]
I just tried it after pulling from master after you posted that, and I'm still getting crashing. Again, thanks for looking into it.

**Comment by Tinob** [comment]
can you share your configuration and what settings are you changing to produce the hang?

**Comment by billywade** [comment]
I'm using the same configuration and settings change as earlier, if that helps. Are there any log files you need?

**Comment by Tinob** [comment]
what backend are you using?

**Comment by billywade** [comment]
Manjaro Linux, stable branch of Arch.

**Comment by Tinob** [comment]
Thanks, will try to test it on linux because in windows Im not able to reproduce it.

**Comment by billywade** [comment]
Thanks! It may just be a weird quirk of OGL.
