### ISSUE TITLE
Using DX12 back-end, colors are partially broken when PP FXs are triggered "On Projection" and "On EFB Copy"

### ISSUE THREAD

**Issue by Fs00** [Tinob/Ishiiruka#98]
When using DirectX 12 backend in the latest version of Ishiiruka (v993), I noticed that all the implementations of Ambient Occlusion get broken. I tested both Ishiiruka's SSAO/SSGI and HamasakiFX's SSAO/SSGI (which normally I use) and I get the same type of artifacts with all of them.
Using DX11 back-end, the problem doesn't occur. The only other version that I tested is v957, where AO was working correctly with DX12.
As soon as I can, I'll provide some screenshots.

**Comment by Tinob** [comment]
thanks for the report it seems that there are problems with the state odf the depth map will try to fix it.

**Comment by Fs00** [comment]
@Tinob How's going? It's been two weeks without any news...
Tell me if there's anything I can do to help you :)

**Comment by Tinob** [comment]
sorry for the lack of updates, im working on a big changes ans stil a few day are left to finish it, and it should also fix this issue.

**Comment by Fs00** [comment]
@Tinob Great news! Keep it up and thanks for the efforts you put in this fantastic fork!

**Comment by Tinob** [comment]
is fixed in the latest version (997)

**Comment by Fs00** [comment]
Yeah, depth map is fixed but now all post-processing effects are broken in v997. Basically, when at least one effect is turned on the game becomes darker. :(

**Comment by Fs00** [comment]
![ishiirukascreenshot_ppbug](https://user-images.githubusercontent.com/30041551/33087140-02a9cf5a-ceea-11e7-9435-8a7c728a9ac1.png)
Here is it

**Comment by Fs00** [comment]
Note that 2D textures aren't affected by that bug. It happens only when using DX12

**Comment by Tinob** [comment]
what configuration/shaders are you using?

**Comment by Fs00** [comment]
I'm using Hamasaki FX, but I've noticed that the bug happens with every shader. It happens also when everything in HamasakiFX shader Options is disabled, so it could be an injector bug

**Comment by Tinob** [comment]
can you test changing the Post Processing triguer?

**Comment by Fs00** [comment]
I've just tested and the bug happens only with trigger set on "On Projection" and "On EFB Copy". However, to get HamasakiFX's SSGI working I need to use "On EFB Copy", otherwise it won't work.

**Comment by Tinob** [comment]
can you send me that shader file, because im testing with the included shaders and cannot duplicate the issue

**Comment by Fs00** [comment]
HamasakiFX Suite is attached to this post. I don't think it will help you because, as I've already said, the bug appens with every shader.
[Hamasaki Vanilla Ultra.glsl.txt](https://github.com/Tinob/Ishiiruka/files/1492662/Hamasaki.Vanilla.Ultra.glsl.txt)

**Comment by Fs00** [comment]
@Tinob You can see two examples here: the first image is 16bit effect applied "On Swap" (working correctly), the second is the same effect applied "On Projection" (effect applied only on background, which is darker than normal)
![ishiiruka_smg16bitok](https://user-images.githubusercontent.com/30041551/33092581-dee67b20-cefa-11e7-8b69-eb716d8cce80.png)
![ishiiruka_smg16bitwrong](https://user-images.githubusercontent.com/30041551/33092582-df066016-cefa-11e7-9f42-da2664343201.png)

**Comment by Tinob** [comment]
yes it has to be something else because i cannot reproduce the issue, can you share your config files and your specs?

**Comment by Fs00** [comment]
My specs are AMD FX-8370E, Nvidia GTX 970, 8GB RAM DDR3.
Where can I find the config file that I must send you?

**Comment by Tinob** [comment]
lets make a experiment to see if the problem is your config file or something in your rig, adda portable.txt file to your ishiiruka folder, in that way the emulator will start in isolated mode and will generate a clean config file, configure folders and selecta shader and try if the issue persist with the default config then  is a problem with your specifig rig and a i will neeed to debug it on your system, if the problem disapears then  the problem is in your config files, you can get them in your Documents\Dolphin Emulator\Config folder.

**Comment by Fs00** [comment]
The problem doesn't disappear although I'm using a clean configuration with DX12. So the problem is related to my rig. For your information, I also tried to update drivers but the problem remained.

**Comment by Tinob** [comment]
ok, just to make tracking of the issue easyer, what is the last version where depth worked and the collors where correct for you?

**Comment by Fs00** [comment]
Colors were right in v993, but the latest version which hadn't any problem was either 972 or 980 (I can't remember exactly).

**Comment by Fs00** [comment]
@Tinob Should this bug be fixed with the latest commits?

**Comment by Tinob** [comment]
still not fixed, but at least i identified the problem, the error is caused by the interaction of antializing and post processing shaders, if you disable antialiasing it will remove the issue, im working to fix it.

**Comment by Fs00** [comment]
Thanks for the info and good work!

**Comment by Tinob** [comment]
uploading version 1017, this issue should be fixed :)

**Comment by Fs00** [comment]
Many thanks, I'll test it tomorrow and I'll tell you!

**Comment by Fs00** [comment]
I've just tested and the bug still happens on my end, even with latest version (1018). Tried with a fresh configuration, but no difference.

**Comment by Fs00** [comment]
**Waaait,** probably I'm missing the point. Older versions (before v980) have this behavior with "On Projection" and "On Swap" in the title screen too. I'll do a few more accurate tests tomorrow and then I'll tell.

**Comment by Fs00** [comment]
Pardon for my confusion with the title! Finally I can confirm that the bug is fixed :)
Strange that I didn't notice that it was caused by AA when trying with a fresh config on v997, anyway what matters is that now everything works correctly 👍
Thanks for your efforts!
